# Generated by Django 2.2.6 on 2019-10-04 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocations',
            name='product',
        ),
        migrations.AddField(
            model_name='allocations',
            name='product',
            field=models.ManyToManyField(
                related_name='UserProductAllocations', to='backend.Product'),
        ),
    ]
