# Generated by Django 2.2.6 on 2019-10-25 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_product_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='documentation',
            field=models.FileField(blank=True, default='', max_length=500, upload_to='documentation'),
        ),
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, default='', max_length=500, upload_to='picture'),
        ),
    ]
