# Generated by Django 2.2.6 on 2019-10-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20191025_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.ManyToManyField(related_name='ProductType', to='backend.Type'),
        ),
    ]
