# Generated by Django 2.2.6 on 2019-10-28 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20191026_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocations',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
