# Generated by Django 2.2.6 on 2019-10-28 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_allocations_message'),
        ('backend', '0007_auto_20191028_1541'),
    ]

    operations = [
    ]
